version: '2'
services:
  mysql:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --skip-character-set-client-handshake
    ports:
      - "3310:3306"
    restart: unless-stopped 
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=Escrito
    volumes:
      - ./bd/init:/docker-entrypoint-initdb.d
      - ./bd/mysql:/var/lib/mysql
  aplicacion:
    build:
      context: ./aplicacion/
      dockerfile: Dockerfile
    tty: true
    restart: unless-stopped
    ports: 
      - "80:80"
    volumes:
    - ./aplicacion/:/var/www/html
networks: 
  default:
    name: red